/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    DialogComponent: typeof import('./src/components/DialogComponent.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FVComboBox: typeof import('./src/components/fluent-wrapper/FVComboBox.vue')['default']
    FVTextField: typeof import('./src/components/fluent-wrapper/FVTextField.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    SignaturePad: typeof import('./src/components/SignaturePad.vue')['default']
  }
}
