# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
  
      # Wechselt in das frontend/ Verzeichnis
      - name: Change to frontend directory
        run: cd frontend
  
      # Installiert Abhängigkeiten im frontend/ Verzeichnis
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
  
      # Führt den Build-Prozess im frontend/ Verzeichnis aus
      - name: Build
        run: npm run build
        working-directory: ./frontend
  
  upload_artifacts:
    
    runs-on: ubuntu-latest
    steps:
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
            name: built-files
            path: /frontend/dist/
  
