# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build App

on:
  push:
    branches: [ "1234" ]
    paths-ignore:
      - 'frontend/dist/**'
  pull_request:
    branches: [ "1234" ]
    paths-ignore:
      - 'frontend/dist/**'

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
  
      # Wechselt in das frontend/ Verzeichnis
      - name: Change to frontend directory
        run: cd frontend
  
      # Installiert Abhängigkeiten im frontend/ Verzeichnis
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
  
      # Führt den Build-Prozess im frontend/ Verzeichnis aus
      - name: Build
        run: npm run build
        working-directory: ./frontend

      - name: Upload Artifacts
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add dist/ --force
          git commit -m "Deploying build files"
          git push
        working-directory: ./frontend

