# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
  
      # Wechselt in das frontend/ Verzeichnis
      - name: Change to frontend directory
        run: cd frontend
  
      # Installiert Abhängigkeiten im frontend/ Verzeichnis
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
  
      # Führt den Build-Prozess im frontend/ Verzeichnis aus
      - name: Build
        run: npm run build
        working-directory: ./frontend
